all:
	(cd src; make -f Makefile_local all)
	(cd gtest; make -f Makefile_local all)
clean:
	(cd src; make -f Makefile_local clean)
	(cd gtest; make -f Makefile_local clean)

createlib:
	( cd src;make -f Makefile_local createlib)
run:
	(cd src;make -f Makefile_local run)
