all:
	(cd src; make -f Makefile_travis all)
	(cd gtest; make -f Makefile_travis all)
clean:
	(cd src; make -f Makefile_travis clean)
	(cd gtest; make -f Makefile_travis clean)

createlib:
	( cd src;make -f Makefile_travis createlib)
